#!/usr/bin/env python3
"""
collect-unresolved.py — Aggregate every "Unresolved / low-confidence" note
the editors and aggregators recorded during a book-cleanup-markdown run into
one book-level file the operator can act on.

Layout it understands (the standard the book-cleanup-markdown skill writes):

    <workdir>/                       (the book's .cleanup-work directory)
      progress.json                  (optional: per-chapter state)
      ch<NNN>/section-NN.report.md   (each editor's full report)
      ch<NNN>/chapter-report.md      (the aggregator's full report)

A report's "unresolved" content is everything under a heading whose title
matches /unresolved|low.confidence|left unchanged|dangling|orphans|seam/
(case-insensitive), up to the next heading. Sections that say only "None"
contribute nothing. If progress.json is present, chapters whose state is not
`reflowed` (failed/pending) are also listed.

Usage:
    python3 collect-unresolved.py <workdir>

Writes <workdir>/unresolved.md and prints its path and a line count.
"""

import json
import os
import re
import sys

HEADING_RE = re.compile(r'^#{1,6}\s+(.*)$')
WANT_RE = re.compile(r'unresolved|low[-\s]?confidence|left unchanged|'
                     r'dangling|orphan|seam', re.I)
NONE_RE = re.compile(r'^\s*[-*]?\s*(none|n\/a|no unresolved|nothing|—)\.?\s*$', re.I)


def sections_of(path):
    """Yield (heading, [lines]) blocks from a markdown report file."""
    blocks = []
    cur_head = None
    cur = []
    try:
        with open(path, 'r', encoding='utf-8') as f:
            for raw in f:
                line = raw.rstrip('\n')
                m = HEADING_RE.match(line)
                if m and not line.startswith('#' * 7):
                    if cur_head is not None:
                        blocks.append((cur_head, cur))
                    cur_head = m.group(1)
                    cur = []
                else:
                    cur.append(line)
        if cur_head is not None:
            blocks.append((cur_head, cur))
    except OSError as e:
        print(f'warning: cannot read {path}: {e}', file=sys.stderr)
    return blocks


def wanted_lines(blocks):
    out = []
    for head, lines in blocks:
        if WANT_RE.search(head):
            content = [l for l in lines if l.strip() and not NONE_RE.match(l)]
            if content:
                out.append((head, content))
    return out


def main():
    if len(sys.argv) != 2:
        print(f'Usage: {sys.argv[0]} <workdir>', file=sys.stderr)
        sys.exit(2)
    workdir = os.path.abspath(sys.argv[1])
    if not os.path.isdir(workdir):
        print(f'not a directory: {workdir}', file=sys.stderr)
        sys.exit(2)

    chapters = sorted(d for d in os.listdir(workdir)
                      if d.startswith('ch') and os.path.isdir(os.path.join(workdir, d)))

    progress = {}
    pj = os.path.join(workdir, 'progress.json')
    if os.path.exists(pj):
        try:
            with open(pj, 'r', encoding='utf-8') as f:
                progress = json.load(f)
        except (OSError, ValueError) as e:
            print(f'warning: cannot parse {pj}: {e}', file=sys.stderr)
    prog_by_ch = {c.get('workDirName') or c.get('number'): c
                  for c in progress.get('chapters', [])}

    out = [f'# Unresolved items — {progress.get("book", workdir)}',
           '',
           f'Generated by collect-unresolved.py from {workdir}',
           '']
    total = 0
    for ch in chapters:
        chdir = os.path.join(workdir, ch)
        picked = []  # (source file, heading, [lines])
        for name in sorted(os.listdir(chdir)):
            if not name.endswith(('.report.md', '-report.md')):
                continue
            blocks = sections_of(os.path.join(chdir, name))
            for head, lines in wanted_lines(blocks):
                picked.append((name, head, lines))
        # progress state line for this chapter
        meta = prog_by_ch.get(ch) or prog_by_ch.get(ch.lstrip('ch'))
        if meta and meta.get('state') not in ('reflowed', 'merged'):
            picked.append(('progress.json', 'state',
                           [f'{meta.get("file", ch)} is {meta.get("state")}']))
        if not picked and not meta:
            continue
        label = ch
        if meta and meta.get('file'):
            label = f'{ch} ({os.path.basename(meta["file"])})'
        out.append(f'## {label}')
        out.append('')
        for src, head, lines in picked:
            out.append(f'_from {src} — {head}_')
            prev_bullet = False
            for l in lines:
                stripped = l.strip()
                if stripped.startswith('- '):
                    out.append(l)
                    prev_bullet = True
                elif prev_bullet and stripped:  # wrapped continuation of the bullet above
                    out[-1] = out[-1] + ' ' + stripped
                else:
                    out.append('- ' + l)
                    prev_bullet = True
            out.append('')
            total += len(lines)

    if total == 0:
        out.append('Nothing unresolved recorded.')
    out.append('')
    # chapters in progress.json with no scanned dir (failed before orienting,
    # a dir removed since, or finished chapters whose orphans/dangling items
    # still need surfacing) — report them from progress.json alone
    for pch in progress.get('chapters', []):
        st = pch.get('state')
        if st in ('reflowed', 'merged') and not (pch.get('orphans') or
                                                pch.get('dangling') or
                                                pch.get('unresolved')):
            continue
        dirname = pch.get('workDirName') or f'ch{int(pch.get("number", 0)):03d}'
        if dirname in chapters:
            continue
        out.append(f'## {dirname} ({os.path.basename(pch.get("file", "?"))})')
        out.append('')
        if st not in ('reflowed', 'merged'):
            out.append(f'_from progress.json — state: {st}_')
        for o in pch.get('orphans', []) or []:
            out.append(f'- orphan footnote definition [^{o}] (no reference in source)')
        for d in pch.get('dangling', []) or []:
            out.append(f'- dangling reference [^{d}] (no definition in file)')
        for u in pch.get('unresolved', []) or []:
            out.append(f'- {u}')
        out.append('')
    dest = os.path.join(workdir, 'unresolved.md')
    with open(dest, 'w', encoding='utf-8') as f:
        f.write('\n'.join(out))
    print(f'wrote {dest} ({total} unresolved line(s), {len(chapters)} chapter dir(s) scanned)')
    sys.exit(0)


if __name__ == '__main__':
    main()
